---
# Global variables for all machines
ansible_python_interpreter: /usr/bin/python3
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

# Timezone
timezone: "America/Toronto"

# Default user
default_user: alesson
